---
dist: trusty
sudo: false

addons:
  apt:
    packages:
      - oracle-java9-installer

language: java
jdk:
  - oraclejdk8
  - openjdk8
  - oraclejdk9

matrix:
  allow_failures:
    - jdk: oraclejdk9
    
script: mvn clean install
